/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_fae_5fapplication_5fargs_2eproto__INCLUDED
#define PROTOBUF_C_fae_5fapplication_5fargs_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _FAEApplication FAEApplication;


/* --- enums --- */


/* --- messages --- */

struct  _FAEApplication
{
  ProtobufCMessage base;
  int32_t appid;
  char *appcategory;
  char *appname;
  char *appworkerid;
  char *annotations;
  char *grayfactors;
  char *localsites;
};
#define FAE__APPLICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fae__application__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL }


/* FAEApplication methods */
void   fae__application__init
                     (FAEApplication         *message);
size_t fae__application__get_packed_size
                     (const FAEApplication   *message);
size_t fae__application__pack
                     (const FAEApplication   *message,
                      uint8_t             *out);
size_t fae__application__pack_to_buffer
                     (const FAEApplication   *message,
                      ProtobufCBuffer     *buffer);
FAEApplication *
       fae__application__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fae__application__free_unpacked
                     (FAEApplication *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FAEApplication_Closure)
                 (const FAEApplication *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fae__application__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_fae_5fapplication_5fargs_2eproto__INCLUDED */
