/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_InjectedArgs_2eproto__INCLUDED
#define PROTOBUF_C_InjectedArgs_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _InjectArgs InjectArgs;


/* --- enums --- */


/* --- messages --- */

struct  _InjectArgs
{
  ProtobufCMessage base;
  char *annotations;
  char *grayfactors;
  char *endpoint;
};
#define INJECT_ARGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&inject_args__descriptor) \
    , NULL, NULL, NULL }


/* InjectArgs methods */
void   inject_args__init
                     (InjectArgs         *message);
size_t inject_args__get_packed_size
                     (const InjectArgs   *message);
size_t inject_args__pack
                     (const InjectArgs   *message,
                      uint8_t             *out);
size_t inject_args__pack_to_buffer
                     (const InjectArgs   *message,
                      ProtobufCBuffer     *buffer);
InjectArgs *
       inject_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   inject_args__free_unpacked
                     (InjectArgs *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*InjectArgs_Closure)
                 (const InjectArgs *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor inject_args__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_InjectedArgs_2eproto__INCLUDED */
