/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "McpAppBeanProto.pb-c.h"
void   mcp_app_bean_proto__init
                     (McpAppBeanProto         *message)
{
  static McpAppBeanProto init_value = MCP_APP_BEAN_PROTO__INIT;
  *message = init_value;
}
size_t mcp_app_bean_proto__get_packed_size
                     (const McpAppBeanProto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mcp_app_bean_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mcp_app_bean_proto__pack
                     (const McpAppBeanProto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mcp_app_bean_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mcp_app_bean_proto__pack_to_buffer
                     (const McpAppBeanProto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mcp_app_bean_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
McpAppBeanProto *
       mcp_app_bean_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (McpAppBeanProto *)
     protobuf_c_message_unpack (&mcp_app_bean_proto__descriptor,
                                allocator, len, data);
}
void   mcp_app_bean_proto__free_unpacked
                     (McpAppBeanProto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &mcp_app_bean_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   receive_result__init
                     (ReceiveResult         *message)
{
  static ReceiveResult init_value = RECEIVE_RESULT__INIT;
  *message = init_value;
}
size_t receive_result__get_packed_size
                     (const ReceiveResult *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &receive_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t receive_result__pack
                     (const ReceiveResult *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &receive_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t receive_result__pack_to_buffer
                     (const ReceiveResult *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &receive_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReceiveResult *
       receive_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReceiveResult *)
     protobuf_c_message_unpack (&receive_result__descriptor,
                                allocator, len, data);
}
void   receive_result__free_unpacked
                     (ReceiveResult *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &receive_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mcp_app_bean_proto__field_descriptors[10] =
{
  {
    "Protocol",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, protocol),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Cmd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, cmd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CompactUri",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, compacturi),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "UserId",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, userid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Sequence",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, sequence),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Opt",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, opt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "UserContext",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, usercontext),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Content",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, content),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Epid",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, epid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ZipFlag",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(McpAppBeanProto, zipflag),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mcp_app_bean_proto__field_indices_by_name[] = {
  1,   /* field[1] = Cmd */
  2,   /* field[2] = CompactUri */
  7,   /* field[7] = Content */
  8,   /* field[8] = Epid */
  5,   /* field[5] = Opt */
  0,   /* field[0] = Protocol */
  4,   /* field[4] = Sequence */
  6,   /* field[6] = UserContext */
  3,   /* field[3] = UserId */
  9,   /* field[9] = ZipFlag */
};
static const ProtobufCIntRange mcp_app_bean_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor mcp_app_bean_proto__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "McpAppBeanProto",
  "McpAppBeanProto",
  "McpAppBeanProto",
  "",
  sizeof(McpAppBeanProto),
  10,
  mcp_app_bean_proto__field_descriptors,
  mcp_app_bean_proto__field_indices_by_name,
  1,  mcp_app_bean_proto__number_ranges,
  (ProtobufCMessageInit) mcp_app_bean_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor receive_result__field_descriptors[1] =
{
  {
    "Protocol",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ReceiveResult, protocol),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned receive_result__field_indices_by_name[] = {
  0,   /* field[0] = Protocol */
};
static const ProtobufCIntRange receive_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor receive_result__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ReceiveResult",
  "ReceiveResult",
  "ReceiveResult",
  "",
  sizeof(ReceiveResult),
  1,
  receive_result__field_descriptors,
  receive_result__field_indices_by_name,
  1,  receive_result__number_ranges,
  (ProtobufCMessageInit) receive_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
